"""empty message

Revision ID: 2d9c890a3aa7
Revises: 4d10b75f337e
Create Date: 2020-03-27 10:18:35.833046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9c890a3aa7'
down_revision = '4d10b75f337e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regular', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regular', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
