"""empty message

Revision ID: 4d10b75f337e
Revises: 6ca20ca1bb3d
Create Date: 2020-03-27 01:51:39.064729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d10b75f337e'
down_revision = '6ca20ca1bb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regular', sa.Column('username', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regular', 'username')
    # ### end Alembic commands ###
