"""empty message

Revision ID: 4de33cff29a2
Revises: bf36bbfb5ace
Create Date: 2020-04-27 14:52:56.718844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4de33cff29a2'
down_revision = 'bf36bbfb5ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formedgrps', 'criteria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formedgrps', sa.Column('criteria', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
