"""empty message

Revision ID: 60f77e01f9d0
Revises: 86b83c51c093
Create Date: 2020-04-16 21:25:58.644231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60f77e01f9d0'
down_revision = '86b83c51c093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formedgrps2',
    sa.Column('minigrp_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('mbr1', sa.String(length=30), nullable=True),
    sa.Column('mbr2', sa.String(length=30), nullable=True),
    sa.Column('criteria', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['grouped.group_id'], ),
    sa.PrimaryKeyConstraint('minigrp_id')
    )
    op.create_table('formedgrps3',
    sa.Column('minigrp_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('mbr1', sa.String(length=30), nullable=True),
    sa.Column('mbr2', sa.String(length=30), nullable=True),
    sa.Column('mbr3', sa.String(length=30), nullable=True),
    sa.Column('criteria', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['grouped.group_id'], ),
    sa.PrimaryKeyConstraint('minigrp_id')
    )
    op.create_table('formedgrps4',
    sa.Column('minigrp_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('mbr1', sa.String(length=30), nullable=True),
    sa.Column('mbr2', sa.String(length=30), nullable=True),
    sa.Column('mbr3', sa.String(length=30), nullable=True),
    sa.Column('mbr4', sa.String(length=30), nullable=True),
    sa.Column('criteria', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['grouped.group_id'], ),
    sa.PrimaryKeyConstraint('minigrp_id')
    )
    op.create_table('formedgrps5',
    sa.Column('minigrp_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('mbr1', sa.String(length=30), nullable=True),
    sa.Column('mbr2', sa.String(length=30), nullable=True),
    sa.Column('mbr3', sa.String(length=30), nullable=True),
    sa.Column('mbr4', sa.String(length=30), nullable=True),
    sa.Column('mbr5', sa.String(length=30), nullable=True),
    sa.Column('criteria', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['grouped.group_id'], ),
    sa.PrimaryKeyConstraint('minigrp_id')
    )
    op.drop_table('formedgrps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formedgrps',
    sa.Column('minigrp_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mbr1', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('mbr2', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('mbr3', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('mbr4', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('mbr5', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('criteria', mysql.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['grouped.group_id'], name='formedgrps_ibfk_1'),
    sa.PrimaryKeyConstraint('minigrp_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('formedgrps5')
    op.drop_table('formedgrps4')
    op.drop_table('formedgrps3')
    op.drop_table('formedgrps2')
    # ### end Alembic commands ###
