"""empty message

Revision ID: 62d73ecefc6b
Revises: 8094c8417d63
Create Date: 2020-03-23 14:05:16.933117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d73ecefc6b'
down_revision = '8094c8417d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generaluser', sa.Column('occupation', sa.String(length=30), nullable=True))
    op.add_column('generaluser', sa.Column('usrtype', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generaluser', 'usrtype')
    op.drop_column('generaluser', 'occupation')
    # ### end Alembic commands ###
