"""empty message

Revision ID: 6418a03d2e1e
Revises: 60f77e01f9d0
Create Date: 2020-04-21 18:35:28.413029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6418a03d2e1e'
down_revision = '60f77e01f9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regular', 'faculty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regular', sa.Column('faculty', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
