"""empty message

Revision ID: 6ca20ca1bb3d
Revises: 62d73ecefc6b
Create Date: 2020-03-25 17:49:42.166394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca20ca1bb3d'
down_revision = '62d73ecefc6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generaluser', sa.Column('type', sa.String(length=20), nullable=True))
    op.drop_column('generaluser', 'usrtype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generaluser', sa.Column('usrtype', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('generaluser', 'type')
    # ### end Alembic commands ###
