"""empty message

Revision ID: 77d61368230c
Revises: 
Create Date: 2020-03-24 01:17:22.778456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d61368230c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('organizer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('regular',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('leadership', sa.String(length=30), nullable=True),
    sa.Column('ethnicity', sa.String(length=30), nullable=True),
    sa.Column('personality', sa.String(length=30), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('hobby', sa.String(length=50), nullable=True),
    sa.Column('faculty', sa.String(length=50), nullable=True),
    sa.Column('work', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Grouped',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=20), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('administrator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrator'], ['organizer.user_id'], ),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('userScore',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['regular.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'feature')
    )
    op.create_table('joinGroup',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Grouped.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['regular.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('joinGroup')
    op.drop_table('userScore')
    op.drop_table('Grouped')
    op.drop_table('regular')
    op.drop_table('organizer')
    op.drop_table('user')
    # ### end Alembic commands ###
