"""empty message

Revision ID: 86b83c51c093
Revises: df7d6c73692a
Create Date: 2020-04-16 20:18:40.870690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b83c51c093'
down_revision = 'df7d6c73692a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formedgrps',
    sa.Column('minigrp_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('mbr1', sa.String(length=30), nullable=True),
    sa.Column('mbr2', sa.String(length=30), nullable=True),
    sa.Column('mbr3', sa.String(length=30), nullable=True),
    sa.Column('mbr4', sa.String(length=30), nullable=True),
    sa.Column('mbr5', sa.String(length=30), nullable=True),
    sa.Column('criteria', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['grouped.group_id'], ),
    sa.PrimaryKeyConstraint('minigrp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formedgrps')
    # ### end Alembic commands ###
