"""empty message

Revision ID: 9138ceed109a
Revises: 
Create Date: 2020-04-14 12:19:39.394850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9138ceed109a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minigroups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minigroups',
    sa.Column('grpBy', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('numPersons', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('grpBy'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
