"""empty message

Revision ID: d3117bb06cc7
Revises: 9138ceed109a
Create Date: 2020-04-14 12:27:33.555515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3117bb06cc7'
down_revision = '9138ceed109a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formedgrps', sa.Column('set_id', sa.Integer(), nullable=True))
    op.drop_constraint('formedgrps_ibfk_1', 'formedgrps', type_='foreignkey')
    op.create_foreign_key(None, 'formedgrps', 'grouped', ['set_id'], ['group_id'])
    op.drop_column('formedgrps', 'administrator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formedgrps', sa.Column('administrator', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'formedgrps', type_='foreignkey')
    op.create_foreign_key('formedgrps_ibfk_1', 'formedgrps', 'organizer', ['administrator'], ['user_id'])
    op.drop_column('formedgrps', 'set_id')
    # ### end Alembic commands ###
