"""empty message

Revision ID: df7d6c73692a
Revises: 9ff1fd401e62
Create Date: 2020-04-15 17:48:16.360649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df7d6c73692a'
down_revision = '9ff1fd401e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('formedgrps_ibfk_4', 'formedgrps', type_='foreignkey')
    op.drop_constraint('formedgrps_ibfk_3', 'formedgrps', type_='foreignkey')
    op.drop_constraint('formedgrps_ibfk_2', 'formedgrps', type_='foreignkey')
    op.drop_constraint('formedgrps_ibfk_5', 'formedgrps', type_='foreignkey')
    op.drop_constraint('formedgrps_ibfk_6', 'formedgrps', type_='foreignkey')
    op.drop_column('formedgrps', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formedgrps', sa.Column('name', mysql.VARCHAR(length=30), nullable=True))
    op.create_foreign_key('formedgrps_ibfk_6', 'formedgrps', 'regular', ['mbr5'], ['user_id'])
    op.create_foreign_key('formedgrps_ibfk_5', 'formedgrps', 'regular', ['mbr4'], ['user_id'])
    op.create_foreign_key('formedgrps_ibfk_2', 'formedgrps', 'regular', ['mbr1'], ['user_id'])
    op.create_foreign_key('formedgrps_ibfk_3', 'formedgrps', 'regular', ['mbr2'], ['user_id'])
    op.create_foreign_key('formedgrps_ibfk_4', 'formedgrps', 'regular', ['mbr3'], ['user_id'])
    # ### end Alembic commands ###
